# Étape 1 : Base Python
FROM python:3.10-slim

# Étape 2 : Dossier de travail
WORKDIR /app

# Étape 3 : Copier les dépendances et les installer
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Étape 4 : Copier le code et le modèle
COPY app.py .
COPY utils.py .
COPY templates/ ./templates/
COPY ecg_model.pkl .

# Étape 5 : Exposer le port 5000 (API Flask)
EXPOSE 5000

# Étape 6 : Lancer l’application
CMD ["python", "app.py"]
